### ISSUE TITLE
Invalid github credentials?

### ISSUE THREAD

**Issue by mapsam** [mapbox/dispatch#109] opened 2017-11-29 18:36 UTC
I selected "yes" when dispatch sent me a message today, and the response was an error code:

<img width="517" alt="screen shot 2017-11-29 at 10 33 44 am" src="https://user-images.githubusercontent.com/1943001/33392465-ff6f6c0c-d4f0-11e7-9133-9ff87d7c4174.png">

Closed the issue manually. 

Issue for reference: https://github.com/mapbox/dispatch-alerts/issues/810

cc @k-mahoney @alulsh

**Comment by k-mahoney** [comment] 2017-11-29 19:53
Hey @mapsam - this has happened a couple times now, in the process of investigating the root cause. Thanks for ticketing with the screenshot, will keep this open for follow up.

**Comment by sbma44** [comment] 2017-12-15 22:21
I ran into this too but couldn't find this ticket, so in the spirit of saving security more reports, here's searchable text:

> error: failed to close GitHub issue 850, {\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}"

**Comment by k-mahoney** [comment] 2017-12-15 22:22
Thanks @sbma44 - hoping to figure out why the Google Drive `patrol` stack isn't playing nice with `dispatch` this coming week.

**Comment by k-mahoney** [comment] 2018-02-07 00:05
This has been resolved by https://github.com/mapbox/dispatch/pull/113

**Closed by k-mahoney** 2018-02-07 00:05 UTC
Labels: bug
